import { setGlobalOptions } from "firebase-functions/v2";
import { onRequest } from "firebase-functions/v2/https";
import { onValueCreated } from "firebase-functions/v2/database";
import * as logger from "firebase-functions/logger";
import fetch from "node-fetch";

const FUNCTION_MAX_INSTANCES = 10;
const MESSAGES_PATH = "/messages/{pushId}";
const AUTHORIZED_USER_ID = "arielgos";

/**
 * Represents the payload shape of a chat message.
 */
type MessagePayload = {
  text: string | null;
  userId: string | null;
  sessionId: string | null;
  createdAt: number | null;
  [key: string]: unknown;
};

type RequestMetadata = {
  method: string;
  path: string;
};

// Configure global options for v2 functions
setGlobalOptions({ maxInstances: FUNCTION_MAX_INSTANCES });

/**
 * Logs the health check request metadata.
 * @param {RequestMetadata} request The request metadata to log.
 */
function logHealthCheck(request: RequestMetadata): void {
  logger.info("Health check received", {
    method: request.method,
    path: request.path,
  });
}

/**
 * Normalizes an unknown value into a message payload.
 * @param {unknown} value The raw value from the database snapshot.
 * @return {MessagePayload | null} A normalized message payload or null.
 */
function normalizeMessagePayload(value: unknown): MessagePayload | null {
  if (typeof value !== "object" || value === null) {
    return null;
  }

  const candidate = value as Partial<MessagePayload>;

  if (typeof candidate.text !== "string" && candidate.text !== null) {
    return null;
  }

  if (typeof candidate.userId !== "string" && candidate.userId !== null) {
    return null;
  }

  return {
    text: candidate.text ?? null,
    userId: candidate.userId ?? null,
    sessionId: candidate.sessionId ?? null,
    createdAt: candidate.createdAt ?? null,
    ...candidate,
  } as MessagePayload;
}

/**
 * Logs the new message event in a safe way.
 * @param {string} pushId The database push ID for the message.
 * @param {MessagePayload | null} message The normalized message payload.
 */
function logNewMessageEvent(
  pushId: string,
  message: MessagePayload | null,
): void {
  logger.info("New message created", {
    pushId,
    message: message ? { ...message } : null,
  });
}

/**
 * Queries the Gemini API to generate a description for a message.
 * @param {string} messageText The text of the message to describe.
 * @return {Promise<string>} A description generated by the Gemini API.
 */
async function queryGeminiForDescription(messageText: string): Promise<string> {
  const geminiApiKey = process.env.GEMINI_API_KEY;

  if (!geminiApiKey) {
    logger.error("GEMINI_API_KEY environment variable not set");
    throw new Error("Gemini API key is required");
  }

  const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${geminiApiKey}`;

  const requestBody = {
    contents: [
      {
        parts: [
          {
            text: `Generate a concise description for the following message content: "${messageText}". 
          The description should be 1-2 sentences and focus on the main topic or purpose of the message.`,
          },
        ],
      },
    ],
  };

  try {
    const response = await fetch(geminiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      throw new Error(
        `Gemini API request failed with status ${response.status}`,
      );
    }

    const data = await response.json();

    // Extract the description from the Gemini response
    if (
      data &&
      data.candidates &&
      data.candidates[0] &&
      data.candidates[0].content
    ) {
      const description = data.candidates[0].content.parts[0]?.text || "";
      return description.trim();
    } else {
      throw new Error("Invalid response from Gemini API");
    }
  } catch (error) {
    logger.error("Error querying Gemini API:", error);
    throw new Error(`Failed to query Gemini API: ${error}`);
  }
}

/**
 * Validates a post against web articles by searching for relevant content.
 * @param {string} messageText The text of the message to validate.
 * @return {Promise<boolean>} True if validation passes, false otherwise.
 */
async function validatePostAgainstWebArticles(
  messageText: string,
): Promise<boolean> {
  // Extract URLs from the message text
  const urlRegex =
    /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/g;
  const urls = messageText.match(urlRegex) || [];

  if (urls.length === 0) {
    // If no URLs found, we can't validate against web content
    logger.info("No URLs found in message for web article validation");
    return true; // Allow messages without links to pass validation
  }

  logger.info("Validating post against web articles", {
    urlCount: urls.length,
    urls: urls,
  });

  // For each URL, we'll ask Gemini to analyze the content
  for (const url of urls) {
    try {
      const analysisResult = await analyzeLinkContentWithGemini(url);

      // If any link analysis fails or returns negative validation,
      // we consider the post invalid
      if (!analysisResult.isValid) {
        logger.info("Link validation failed", {
          url: url,
          reason:
            analysisResult.reason || "Content not suitable for validation",
        });
        return false;
      }
    } catch (error) {
      logger.error("Error analyzing link content", {
        url: url,
        error: error,
      });
      // If we can't analyze a link, we'll still allow the message to pass
      // but log the error for monitoring
    }
  }

  return true;
}

/**
 * Analyzes content of a web link using Gemini API.
 * @param {string} url The URL to analyze.
 * @return {Promise<{isValid: boolean, reason?: string}>} Analysis result.
 */
async function analyzeLinkContentWithGemini(
  url: string,
): Promise<{ isValid: boolean; reason?: string }> {
  const geminiApiKey = process.env.GEMINI_API_KEY;

  if (!geminiApiKey) {
    logger.error("GEMINI_API_KEY environment variable not set");
    return { isValid: false, reason: "Gemini API key not configured" };
  }

  const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${geminiApiKey}`;

  const requestBody = {
    contents: [
      {
        parts: [
          {
            text: `Analyze the content of this web page URL: ${url}. 
            Determine if the content is factual, reliable, and appropriate for validation purposes. 
            Return a JSON object with "isValid": true/false and "reason": string explaining your decision.`,
          },
        ],
      },
    ],
  };

  try {
    const response = await fetch(geminiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      throw new Error(
        `Gemini API request failed with status ${response.status}`,
      );
    }

    const data = await response.json();

    // Extract the analysis from the Gemini response
    if (
      data &&
      data.candidates &&
      data.candidates[0] &&
      data.candidates[0].content
    ) {
      const analysisText = data.candidates[0].content.parts[0]?.text || "";

      // Try to parse the JSON response from Gemini
      try {
        const analysis = JSON.parse(analysisText);
        return {
          isValid: analysis.isValid === true,
          reason: analysis.reason || "No reason provided",
        };
      } catch (parseError) {
        // If parsing fails, return a default response
        logger.warn("Failed to parse Gemini analysis result as JSON", {
          analysisText: analysisText,
          error: parseError,
        });

        // Default to allowing the content if we can't parse it properly
        return { isValid: true, reason: "Could not parse analysis result" };
      }
    } else {
      throw new Error("Invalid response from Gemini API");
    }
  } catch (error) {
    logger.error("Error analyzing link content with Gemini:", error);
    return { isValid: false, reason: `Failed to analyze link: ${error}` };
  }
}

/**
 * Exposes a simple health endpoint for monitoring.
 */
export const health = onRequest((request, response) => {
  logHealthCheck({
    method: request.method,
    path: request.path,
  });

  response.status(200).send("OK");
});

/**
 * Handles newly created messages in the Realtime Database.
 */
export const onNewMessageCreated = onValueCreated(
  MESSAGES_PATH,
  async (event) => {
    if (!event.data.exists()) {
      return null;
    }

    const pushId = event.params.pushId;
    const message = normalizeMessagePayload(event.data.val());

    if (!message) {
      logger.warn("Received message payload with an unexpected format", {
        pushId,
      });

      return null;
    }

    if (message.userId != AUTHORIZED_USER_ID) {
      logger.warn("Received message payload from an unauthorized user", {
        pushId,
        userId: message.userId,
      });
      return null;
    }

    logNewMessageEvent(pushId, message);

    try {
      // Query Gemini API for a description of the message
      const description = await queryGeminiForDescription(message.text || "");

      logger.info("Generated description from Gemini API", {
        pushId,
        description: description,
      });

      // Validate the post against web articles
      const isValid = await validatePostAgainstWebArticles(message.text || "");

      logger.info("Post validation result", {
        pushId,
        isValid: isValid,
      });

      // Add future async work here, for example:
      // await sendNotification(pushId, message);
    } catch (error) {
      logger.error("Error processing new message", {
        pushId,
        error: error,
      });
    }

    return null;
  },
);
